name: Python SDK Tests

on:
  push:
    branches: [main]
    paths:
      - "python/**"
      - "js-sdk-server/**"
  pull_request:
    branches: [main]
    paths:
      - "python/**"
      - "js-sdk-server/**"
jobs:
  test:
    runs-on: warp-ubuntu-latest-x64-2x
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run tests
        working-directory: python
        env:
          LIT_POLYGLOT_SDK_TEST_PRIVATE_KEY: ${{ secrets.LIT_POLYGLOT_SDK_TEST_PRIVATE_KEY }}
        run: |
          pytest tests/ -v
          if [ -f lit_python_sdk/server.log ]; then
            echo "Server log contents:"
            cat lit_python_sdk/server.log
          fi
